name: Flarum Frontend Jobs

on:
  workflow_call:
    inputs:
      enable_bundlewatch:
        description: "Enable Bundlewatch?"
        type: boolean
        default: false
        required: false
      enable_prettier:
        description: "Enable Prettier?"
        type: boolean
        default: true
        required: false
      enable_typescript:
        description: "Enable TypeScript?"
        type: boolean
        default: true
        required: false
        
      frontend_directory:
        description: The directory of the project where frontend code is located. This should contain a `package.json` file.
        type: string
        required: false
        default: './js'
      main_git_branch:
        description: The main git branch to use for the workflow.
        type: string
        required: false
        default: main
      node_version:
        description: The node version to use for the workflow.
        type: number
        required: false
        default: 16
    secrets:
      bundlewatch_github_token:
        description: The GitHub token to use for Bundlewatch.
        required: false        

env:
  cache_dependency_path: ${{ format('{0}/yarn.lock', inputs.frontend_directory) }}

jobs:
  bundlewatch:
    name: Bundlewatch
    runs-on: ubuntu-latest
    if: inputs.enable_bundlewatch

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.cache_dependency_path }}

      - name: Build production assets
        uses: flarum/action-build@2
        with:
          github_token: ${{ secrets.github_token }}
          build_script: build
          package_manager: yarn
          do_not_commit: true

      - name: Check bundle size change
        run: node_modules/.bin/bundlewatch --config .bundlewatch.config.json
        working-directory: ${{ inputs.frontend_directory }}
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.bundlewatch_github_token }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    if: inputs.enable_prettier

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.cache_dependency_path }}

      - name: Install JS dependencies
        run: yarn install --immutable
        working-directory: ${{ inputs.frontend_directory }}

      - name: Check JS formatting
        run: yarn run format-check
        working-directory: ${{ inputs.frontend_directory }}

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    if: inputs.enable_typescript

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.cache_dependency_path }}

      - name: Install JS dependencies
        run: yarn --frozen-lockfile
        working-directory: ${{ inputs.frontend_directory }}

      - name: Typecheck
        run: yarn run check-typings
        working-directory: ${{ inputs.frontend_directory }}

  type-coverage:
    name: Type Coverage
    runs-on: ubuntu-latest
    if: inputs.enable_typescript

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.cache_dependency_path }}

      - name: Install JS dependencies
        run: yarn --frozen-lockfile
        working-directory: ${{ inputs.frontend_directory }}

      - name: Check type coverage
        run: yarn run check-typings-coverage
        working-directory: ${{ inputs.frontend_directory }}

  build:
    name: Build
    runs-on: ubuntu-latest
    if: "always() && !contains(needs.*.result, 'failed') && !contains(needs.*.result, 'cancelled')"
    needs: [bundlewatch, prettier, typecheck, type-coverage]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: "yarn"
          cache-dependency-path: ${{ env.cache_dependency_path }}

      - name: Testing
        run: echo "${{ github.ref}} ${{ inputs.main_git_branch }} ${{ github.event_name}}"

      # Our action will install npm/yarn, cd into `${{ inputs.frontend_directory }}`, build dist JS and typings,
      # then commit and upload any changes iff we are on the main branch and have just pushed.
      - name: Build production JS
        uses: flarum/action-build@2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          package_manager: yarn
          typings_script: build-typings
          do_not_commit: ${{ github.ref != format('refs/heads/{0}', inputs.main_git_branch) || github.event_name != 'push' }}
